model:
  core_model_name: "meta-llama/Meta-Llama-3-8B"
  vocab_size: 8192
  hidden_size: 768
  num_hidden_layers: 2
  num_attention_heads: 2
  max_position_embeddings: 1024
  
tokenizer:
  tokenizer_name: "./tokenizers/trained_tokenizers"
  vocab_size: 8192
  custom_tokenizer: true

dataset:
  train_pickle_file_path: "./data/tcga_data/split/Llama-3.3-70B-processed-200-split-variations/tcga_train_variations.pkl"
  val_pickle_file_path: "./data/tcga_data/split/Llama-3.3-70B-processed-200-split-variations/tcga_val_variations.pkl"
  embeddings_dim_size: 768
  max_seq_length: 1024
  random_choice_report: true

training:
  output_dir: "./pathollama_train"
  eval_strategy: "epoch"
  do_train: true
  do_eval: true
  save_strategy: "steps"
  save_steps: 800
  logging_steps: 10
  lr_scheduler_type: "linear"
  logging_strategy: "steps"
  #logging_dir: "./runs"
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 1
  num_train_epochs: 20
  learning_rate: 0.0008
  dataloader_num_workers: 12
  fp16: false
  bf16: true
  remove_unused_columns: false
  disable_tqdm: false
  torch_compile: false
  report_to: ["tensorboard"]


