model:
  core_model_name: "meta-llama/Meta-Llama-3-8B"
  vocab_size: 32000
  hidden_size: 768
  num_hidden_layers: 4
  num_attention_heads: 4
  max_position_embeddings: 4096
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2

dataset:
  pickle_file_path: "./data/tcga_data/tcga_titan_embeddings_reports.pkl"
  embeddings_dim_size: 768
  max_seq_len: 4096

training:
  output_dir: "./pathollama_train"
  evaluation_strategy: "steps"
  save_strategy: "steps"
  save_steps: 20
  logging_steps: 10
  per_device_train_batch_size: 2
  num_train_epochs: 1
  learning_rate: 1e-4
  fp16: true
  remove_unused_columns: false
  report_to: ["tensorboard"]

