model:
  core_model_name: "meta-llama/Meta-Llama-3-8B"
  load_checkpoint_path: null
  vocab_size: 32768
  hidden_size: 768
  num_hidden_layers: 2
  num_attention_heads: 2
  max_position_embeddings: 1024
  
tokenizer:
  tokenizer_name: "./tokenizers/trained_tokenizers/32768_pubmed/"
  vocab_size: 32768
  custom_tokenizer: true

dataset:
  train_pickle_file_path: "../../data/processed/titan_slide_features/titan_slide_features_conch_v15.h5"
  val_data_ratio: 0.2
  embeddings_dim_size: 768
  max_seq_length: 1024

training:
  output_dir: "./pathollama_barrett_train"
  eval_strategy: "epoch"
  do_train: true
  do_eval: true
  save_strategy: "steps"
  save_steps: 3000
  logging_steps: 10
  lr_scheduler_type: "linear"
  logging_strategy: "steps"
  #logging_dir: "./runs"
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 1
  num_train_epochs: 100
  learning_rate: 0.001
  dataloader_num_workers: 12
  fp16: false
  bf16: true
  remove_unused_columns: false
  disable_tqdm: false
  torch_compile: false
  report_to: ["tensorboard"]


